### ISSUE TITLE
Connector tokens are not destroyed correctly

### ISSUE THREAD

**Issue by xiongchiamiov** [Twingate-Labs/pulumi-twingate#10]
I've written up a long description of the behavior I'm seeing at https://forum.twingate.com/t/api-generated-connector-tokens-are-invalid/314 .  In short, after generating more than a single token for a connector, the tokens get invalidated after 10 minutes; this implies that:

1. Twingate only supports a single token per connector
2. Pulumi is not destroying the old token

I can't find a way to view existing tokens attached to a connector to verify this is what's happening, but it seems to make sense from my blackbox view.

I see that the terraform provider [does have a delete function for tokens](https://github.com/Twingate/terraform-provider-twingate/blob/main/twingate/internal/provider/resource/connector-tokens.go#L75).  I don't know really anything about terraform so I can't verify that it is actually working, but that's why I decided to open this issue here instead of there, because it implies that maybe the problem is in the Pulumi overlay.  I don't know though.

I'm also not sure how exactly this is intended to work on the backend.  I could see a world where the automation _doesn't_ delete old tokens (so a deploy is more graceful) and instead the Twingate backend does the auto-invalidation after ten minutes, but _of the old token_; if that's the intended experience, then it's a bug there instead of here.

If it would be helpful, I can modify https://github.com/Twingate-Labs/pulumi-twingate/blob/master/examples/connector-aws-ecs/__main__.py to create a reproduction example (I have a repository full of these for bugs in the aws-native provider).  I think the main thing though is to do something that forces recreation of a token on a connector, and then wait 10 minutes and observe the newly-generated token is no longer valid.

**Comment by chenbishop** [comment]
@xiongchiamiov apologies for the late reply.

Twingate only supports a single token per connector and whenever a new token is generated, the old token would be voided.

I believe you would like to rotate your token regularly.

The best way I can think of is adding date as part of the token Pulumi resource name. e.g.

modify the following line (line 130 at [here](https://github.com/Twingate-Labs/pulumi-twingate/blob/master/examples/connector-aws-ecs/__main__.py)):
``` 
connector_token = tg.TwingateConnectorTokens(f"connector_token_{i}", connector_id=connector.id)
```

to 

```
from datetime import datetime 
connector_token = tg.TwingateConnectorTokens(f"connector_token_{i}_{datetime.now().month}_{datetime.now().year}", connector_id=connector.id)
```

With this you can schedule your Pulumi script to execute every month to trigger
1. token refresh
2. connector redeploy with the new token

Please let me know if this helps.
