### ISSUE TITLE
Docs on Pulumi.com show incorrect configuration variable name

### ISSUE THREAD

**Issue by Spittal** [Twingate-Labs/pulumi-twingate#6]
Hey friends, looks like the docs on the Pulumi official docs show the incorrect name for the `apiToken`. Just a heads up!

In the docs it shows

```
pulumi config set twingate:apiKey XXXXXX --secret
```

When it should be

```
pulumi config set twingate:apiToken XXXXXX --secret
```

https://www.pulumi.com/registry/packages/twingate/installation-configuration/

![image](https://user-images.githubusercontent.com/1229177/179099681-4ad22f61-ef1f-4054-8b64-0ea141a5a801.png)

**Comment by emrul** [comment]
Hi @Spittal - thanks for reporting this - we will get this updated ASAP!
