### ISSUE TITLE
Name is no longer automated

### ISSUE THREAD

**Issue by KaoruDev** [Twingate-Labs/pulumi-twingate#8]
I upgraded from `0.0.22` to `0.0.32` and noticed that the `TwingateRemoteNetwork` now _requires_ `name` to be passed in. This becomes a problem when trying to replace the network with the same name because now we have to auto-generate the Pulumi suffix.

Ask is to have the `name` be optional and follow [Pulumi's Auto-name behavior](https://www.pulumi.com/docs/intro/concepts/resources/names/#autonaming).

**Comment by emrul** [comment]
Hi @KaoruDev - thanks for reporting this. `Name` should be optional, I'll investigate this and report back.

**Comment by chenbishop** [comment]
Resolved.
